--
-- PostgreSQL database dump
--

\restrict xbFG3bOAPAHuSfDFsGhtT5jJLuBXz9BhB3co7JPnP9fDFi0Ciwpg51W1dFO0uJq

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: update_chat_last_message(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_chat_last_message() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE "Chats"
    SET last_message_at = NEW.sent_at
    WHERE chat_id = NEW.chat_id;

    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Activity" (
    activity_id bigint NOT NULL,
    creator_id bigint NOT NULL,
    chat_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    event_time timestamp without time zone NOT NULL,
    is_cancelled boolean
);


--
-- Name: Activity_Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Activity_Users" (
    activity_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: Activity_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Activity_activity_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Activity_activity_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Activity_activity_id_seq" OWNED BY public."Activity".activity_id;


--
-- Name: Chat_Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Chat_Users" (
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamp without time zone DEFAULT now() NOT NULL,
    id bigint NOT NULL
);


--
-- Name: Chat_Users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Chat_Users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Chat_Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Chats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Chats" (
    chat_id bigint NOT NULL,
    name character varying(255),
    is_group boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    last_message_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: Chats_chat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Chats_chat_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Chats_chat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Chats_chat_id_seq" OWNED BY public."Chats".chat_id;


--
-- Name: Friendships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Friendships" (
    friendship_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: Friendships_friendship_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Friendships_friendship_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Friendships_friendship_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Friendships_friendship_id_seq" OWNED BY public."Friendships".friendship_id;


--
-- Name: Message_Seen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Message_Seen" (
    id bigint NOT NULL,
    message_id bigint NOT NULL,
    user_id bigint NOT NULL,
    seen_at timestamp without time zone DEFAULT now()
);


--
-- Name: Message_Seen_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Message_Seen_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Message_Seen_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Message_Seen_id_seq" OWNED BY public."Message_Seen".id;


--
-- Name: Messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Messages" (
    message_id bigint NOT NULL,
    chat_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    content character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'sending'::character varying NOT NULL,
    sent_at timestamp without time zone DEFAULT now() NOT NULL,
    reply_to_message_id bigint,
    reply_preview character varying(255),
    reply_sender_name character varying(255),
    CONSTRAINT "Messages_status_check" CHECK (((status)::text = ANY (ARRAY[('sending'::character varying)::text, ('sent'::character varying)::text, ('seen'::character varying)::text])))
);


--
-- Name: Messages_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Messages_message_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Messages_message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Messages_message_id_seq" OWNED BY public."Messages".message_id;


--
-- Name: User_Images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."User_Images" (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    image_path character varying(255) NOT NULL
);


--
-- Name: User_Images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."User_Images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: User_Images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."User_Images_id_seq" OWNED BY public."User_Images".id;


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    country_of_origin character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    profile_image_id bigint,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    bio character varying(1000)
);


--
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Users_id_seq" OWNED BY public."Users".id;


--
-- Name: chat_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_users (
    id bigint NOT NULL,
    chat_id bigint,
    joined_at timestamp(6) without time zone,
    user_id bigint
);


--
-- Name: chat_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    notification_id bigint NOT NULL,
    user_id bigint NOT NULL,
    type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    message character varying(255),
    actor_user_id bigint,
    activity_id bigint,
    chat_id bigint,
    message_id bigint,
    is_seen boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notifications_notification_id_seq OWNED BY public.notifications.notification_id;


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(512) NOT NULL,
    user_id bigint
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Activity activity_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity" ALTER COLUMN activity_id SET DEFAULT nextval('public."Activity_activity_id_seq"'::regclass);


--
-- Name: Chats chat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chats" ALTER COLUMN chat_id SET DEFAULT nextval('public."Chats_chat_id_seq"'::regclass);


--
-- Name: Friendships friendship_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Friendships" ALTER COLUMN friendship_id SET DEFAULT nextval('public."Friendships_friendship_id_seq"'::regclass);


--
-- Name: Message_Seen id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen" ALTER COLUMN id SET DEFAULT nextval('public."Message_Seen_id_seq"'::regclass);


--
-- Name: Messages message_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages" ALTER COLUMN message_id SET DEFAULT nextval('public."Messages_message_id_seq"'::regclass);


--
-- Name: User_Images id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User_Images" ALTER COLUMN id SET DEFAULT nextval('public."User_Images_id_seq"'::regclass);


--
-- Name: Users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users" ALTER COLUMN id SET DEFAULT nextval('public."Users_id_seq"'::regclass);


--
-- Name: notifications notification_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications ALTER COLUMN notification_id SET DEFAULT nextval('public.notifications_notification_id_seq'::regclass);


--
-- Data for Name: Activity; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Activity" (activity_id, creator_id, chat_id, title, description, latitude, longitude, created_at, updated_at, event_time, is_cancelled) FROM stdin;
1	1	1	Swimming	We gonna swim	-6.157384	108.743840	2026-07-10 21:21:36.61924	2026-07-10 21:21:36.61924	2026-07-10 06:00:00	f
2	1	2	ehehg	ehejeh	-6.208800	106.845600	2026-07-25 15:10:09.049607	2026-07-25 15:10:09.049607	2026-07-25 12:00:00	f
3	1	3	Hanging out	Meeting new people	-6.208800	106.845600	2026-07-25 19:02:18.056256	2026-07-25 19:02:18.056256	2026-07-25 03:00:00	f
4	1	4	jakwwj	ejejej	-6.224180	106.869078	2026-08-01 17:40:19.929366	2026-08-01 17:40:19.929366	2026-08-01 04:00:00	f
5	3	5	Exploring Cilagon	We go to Cilagon and then Anyer	-6.020672	106.033057	2026-08-01 18:00:16.732593	2026-08-01 18:00:16.732593	2026-08-01 16:00:00	f
6	2	6	Fishing	Catching dirty fish to feed my dog	-6.081733	106.910352	2026-08-01 18:07:01.23317	2026-08-01 18:07:01.23317	2026-08-01 06:00:00	f
7	1	9	Jumping off monas with parachute	Just jump its ok	-6.175286	106.827149	2026-08-02 13:28:54.212444	2026-08-02 13:28:54.212444	2026-08-02 03:00:00	f
8	1	10	Climbing to 3000	Bring lots of water and some snacks	-6.779218	106.963115	2026-08-02 13:29:44.420147	2026-08-02 13:29:44.420147	2026-08-02 04:15:00	f
9	2	36	climbing mount Pangarango	we gonna climb 7 hours in darkness to see the sunrise	-6.770304	106.964735	2026-08-11 15:08:37.350388	2026-08-11 15:08:37.350388	2026-08-11 06:00:00	f
10	1	37	Waving at the boats	we gonna do.nothing smart	-6.083288	106.911917	2026-08-11 15:40:33.54057	2026-08-11 15:40:33.54057	2026-08-11 06:00:00	f
11	1	38	ejdjd	snsnj	-6.214151	106.866930	2026-08-13 15:23:54.524427	2026-08-13 15:23:54.524427	2026-08-13 12:00:00	f
12	2	41	Bdsm practice	Retha asked	-6.116703	106.826705	2026-08-14 06:22:51.398218	2026-08-14 06:22:51.398218	2026-08-14 06:00:00	f
13	2	42	bdsm practice	retha asked	-6.091962	106.781534	2026-08-14 06:23:18.93283	2026-08-14 06:23:18.93283	2026-08-14 12:00:00	f
14	2	43	Hitchhiking to Yogia	lol	-6.134666	106.935039	2026-08-16 14:18:33.246882	2026-08-16 14:18:33.246882	2026-08-16 03:00:00	f
15	2	44	Finding the grave of grandfrather Gingis	its around here, im pretty sure	60.712762	106.515665	2026-08-16 14:20:18.168479	2026-08-16 14:20:18.168479	2026-08-16 06:00:00	f
\.


--
-- Data for Name: Activity_Users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Activity_Users" (activity_id, user_id, joined_at) FROM stdin;
1	1	2026-07-10 21:21:36.61924
1	2	2026-07-10 21:22:24.941023
2	1	2026-07-25 15:10:09.049607
2	2	2026-07-25 18:55:48.110828
3	1	2026-07-25 19:02:18.056256
3	3	2026-07-31 18:06:07.324516
1	3	2026-07-31 18:06:11.621861
4	1	2026-08-01 17:40:19.929366
5	3	2026-08-01 18:00:16.732593
4	2	2026-08-01 18:06:26.592218
5	2	2026-08-01 18:06:30.447584
6	2	2026-08-01 18:07:01.23317
7	1	2026-08-02 13:28:54.212444
8	1	2026-08-02 13:29:44.420147
1	4	2026-08-02 14:06:29.14152
9	2	2026-08-11 15:08:37.350388
10	1	2026-08-11 15:40:33.54057
11	1	2026-08-13 15:23:54.524427
10	5	2026-08-13 17:58:04.868972
6	5	2026-08-13 17:58:06.838361
3	5	2026-08-13 17:58:09.74223
9	5	2026-08-13 17:58:19.675842
8	5	2026-08-13 17:58:23.870083
5	5	2026-08-13 17:58:28.955241
6	3	2026-08-13 19:17:34.200376
7	3	2026-08-13 19:17:47.593994
10	3	2026-08-13 19:19:26.05357
7	2	2026-08-14 02:28:04.059898
3	2	2026-08-14 02:28:06.298463
11	2	2026-08-14 02:28:08.493184
12	2	2026-08-14 06:22:51.398218
13	2	2026-08-14 06:23:18.93283
14	2	2026-08-16 14:18:33.246882
15	2	2026-08-16 14:20:18.168479
\.


--
-- Data for Name: Chat_Users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Chat_Users" (chat_id, user_id, joined_at, id) FROM stdin;
1	1	2026-07-10 21:21:36.601701	1
1	2	2026-07-10 21:22:24.939498	2
2	1	2026-07-25 15:10:09.041486	3
2	2	2026-07-25 18:55:48.107567	4
3	1	2026-07-25 19:02:18.045115	5
3	3	2026-07-31 18:06:07.322905	6
1	3	2026-07-31 18:06:11.620567	7
4	1	2026-08-01 17:40:19.9187	8
5	3	2026-08-01 18:00:16.723673	9
4	2	2026-08-01 18:06:26.590496	10
5	2	2026-08-01 18:06:30.446341	11
6	2	2026-08-01 18:07:01.225237	12
7	1	2026-08-01 19:03:25.368683	13
7	2	2026-08-01 19:03:25.368683	14
8	1	2026-08-01 19:59:25.247547	15
8	3	2026-08-01 19:59:25.247547	16
9	1	2026-08-02 13:28:54.194958	17
10	1	2026-08-02 13:29:44.412212	18
1	4	2026-08-02 14:06:29.139802	19
11	4	2026-08-02 14:11:00.593228	20
11	2	2026-08-02 14:11:00.593228	21
12	4	2026-08-02 14:11:44.763014	22
12	1	2026-08-02 14:11:44.763014	23
36	2	2026-08-11 15:08:37.340677	24
37	1	2026-08-11 15:40:33.532999	25
38	1	2026-08-13 15:23:54.514883	26
37	5	2026-08-13 17:58:04.853429	27
6	5	2026-08-13 17:58:06.835727	28
3	5	2026-08-13 17:58:09.740454	29
36	5	2026-08-13 17:58:19.66342	30
10	5	2026-08-13 17:58:23.858497	31
5	5	2026-08-13 17:58:28.952621	32
39	5	2026-08-13 17:58:57.910454	33
39	1	2026-08-13 17:58:57.910454	34
6	3	2026-08-13 19:17:34.19434	35
9	3	2026-08-13 19:17:47.590862	36
40	3	2026-08-13 19:18:18.526272	37
40	2	2026-08-13 19:18:18.526272	38
37	3	2026-08-13 19:19:26.052955	39
9	2	2026-08-14 02:28:04.05871	40
3	2	2026-08-14 02:28:06.288346	41
38	2	2026-08-14 02:28:08.491526	42
41	2	2026-08-14 06:22:51.386181	43
42	2	2026-08-14 06:23:18.925782	44
43	2	2026-08-16 14:18:33.226181	45
44	2	2026-08-16 14:20:18.150173	46
\.


--
-- Data for Name: Chats; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Chats" (chat_id, name, is_group, created_at, last_message_at) FROM stdin;
5	Exploring Cilagon	t	2026-08-01 18:00:16.714346	2026-08-02 19:53:00.920257
4	jakwwj	t	2026-08-01 17:40:19.909264	2026-08-02 15:08:50.142565
10	Climbing to 3000	t	2026-08-02 13:29:44.405948	2026-08-02 15:28:25.451662
2	ehehg	t	2026-07-25 15:10:09.035022	2026-08-02 15:33:06.619022
11	\N	f	2026-08-02 14:11:00.590664	2026-08-02 15:34:44.594652
3	Hanging out	t	2026-07-25 19:02:18.040275	2026-08-02 15:44:46.338464
36	climbing mount Pangarango	t	2026-08-11 15:08:37.332453	2026-08-11 15:08:37.330366
12	\N	f	2026-08-02 14:11:44.753572	2026-08-11 15:39:30.06426
37	Waving at the boats	t	2026-08-11 15:40:33.524182	2026-08-11 15:40:33.522699
38	ejdjd	t	2026-08-13 15:23:54.511551	2026-08-13 15:23:54.509293
7	\N	f	2026-08-01 19:03:25.366748	2026-08-13 17:28:26.72203
39	Mića + Rossa	f	2026-08-13 17:58:57.903734	2026-08-13 17:58:57.917048
6	Fishing	t	2026-08-01 18:07:01.216747	2026-08-13 19:19:36.397855
8	\N	f	2026-08-01 19:59:25.239022	2026-08-14 02:03:43.943025
41	Bdsm practice	t	2026-08-14 06:22:51.382388	2026-08-14 06:22:51.37759
42	bdsm practice	t	2026-08-14 06:23:18.918573	2026-08-14 06:23:18.91719
9	Jumping off monas with parachute	t	2026-08-02 13:28:54.198231	2026-08-16 14:17:25.826152
43	Hitchhiking to Yogia	t	2026-08-16 14:18:33.231431	2026-08-16 14:18:33.226181
44	Finding the grave of grandfrather Gingis	t	2026-08-16 14:20:18.16069	2026-08-16 14:20:18.150173
40	Djura + Filip	f	2026-08-13 19:18:18.518038	2026-08-16 15:24:07.160948
1	Swimming	t	2026-07-10 21:21:36.592317	2026-08-16 15:30:31.827517
\.


--
-- Data for Name: Friendships; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Friendships" (friendship_id, sender_id, receiver_id, status, created_at) FROM stdin;
2	1	2	ACCEPTED	2026-07-10 21:23:38.765664
5	5	1	ACCEPTED	2026-08-13 17:58:49.692496
8	3	1	ACCEPTED	2026-08-13 19:18:29.910025
6	5	2	ACCEPTED	2026-08-13 18:01:14.115448
\.


--
-- Data for Name: Message_Seen; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Message_Seen" (id, message_id, user_id, seen_at) FROM stdin;
1	1	2	2026-07-10 21:22:26.732442
2	2	1	2026-07-10 21:23:47.0683
3	3	1	2026-07-10 21:23:47.082602
4	4	1	2026-07-10 21:23:47.089554
5	5	1	2026-07-25 18:56:25.399271
6	1	3	2026-07-31 18:06:37.564506
7	2	3	2026-07-31 18:06:37.570749
8	3	3	2026-07-31 18:06:37.574888
9	4	3	2026-07-31 18:06:37.580772
10	5	3	2026-07-31 18:06:37.585072
11	6	3	2026-07-31 18:06:37.590249
12	7	3	2026-07-31 18:06:37.59479
13	6	2	2026-07-31 18:07:03.438305
14	7	2	2026-07-31 18:07:03.446461
15	8	3	2026-08-01 18:00:38.479001
16	9	3	2026-08-01 18:00:38.513839
17	29	1	2026-08-01 19:31:01.571468
18	30	1	2026-08-01 19:31:01.597275
19	31	1	2026-08-01 19:31:01.603408
20	32	1	2026-08-01 19:31:01.610763
21	33	1	2026-08-01 19:31:01.615293
22	34	1	2026-08-01 19:31:01.626522
23	35	1	2026-08-01 19:31:01.635128
24	36	1	2026-08-01 19:31:01.642214
25	37	1	2026-08-01 19:31:01.647637
26	38	1	2026-08-01 19:31:01.658656
27	39	1	2026-08-01 19:31:01.667121
28	40	1	2026-08-01 19:31:01.674079
29	1	4	2026-08-02 14:06:31.818023
30	2	4	2026-08-02 14:06:31.841579
31	3	4	2026-08-02 14:06:31.845672
32	4	4	2026-08-02 14:06:31.851142
33	5	4	2026-08-02 14:06:31.857875
34	6	4	2026-08-02 14:06:31.867565
35	7	4	2026-08-02 14:06:31.872907
36	10	4	2026-08-02 14:06:31.878042
37	11	4	2026-08-02 14:06:31.884256
38	12	4	2026-08-02 14:06:31.890105
39	13	4	2026-08-02 14:06:31.895213
40	14	4	2026-08-02 14:06:31.900335
41	15	4	2026-08-02 14:06:31.906457
42	16	4	2026-08-02 14:06:31.912
43	17	4	2026-08-02 14:06:31.916726
44	18	4	2026-08-02 14:06:31.921945
45	19	4	2026-08-02 14:06:31.9263
46	20	4	2026-08-02 14:06:31.930398
47	21	4	2026-08-02 14:06:31.935457
48	22	4	2026-08-02 14:06:31.939513
49	23	4	2026-08-02 14:06:31.943786
50	24	4	2026-08-02 14:06:31.947936
51	25	4	2026-08-02 14:06:31.952058
52	26	4	2026-08-02 14:06:31.956191
53	27	4	2026-08-02 14:06:31.960929
54	28	4	2026-08-02 14:06:31.966056
55	47	1	2026-08-02 14:29:32.577565
56	57	4	2026-08-02 15:33:31.263494
57	48	2	2026-08-02 15:34:29.036836
58	61	2	2026-08-02 15:34:29.063522
59	62	4	2026-08-02 15:35:05.248301
60	63	4	2026-08-02 15:35:05.256105
61	49	1	2026-08-02 15:44:31.533791
62	41	5	2026-08-13 17:58:38.540209
63	8	5	2026-08-13 17:58:41.550009
64	9	5	2026-08-13 17:58:41.562756
65	52	5	2026-08-13 17:58:41.570551
66	54	5	2026-08-13 17:58:41.570551
67	55	5	2026-08-13 17:58:41.58189
68	56	5	2026-08-13 17:58:41.588205
69	67	5	2026-08-13 17:58:41.592735
70	46	3	2026-08-13 19:18:32.55083
71	65	3	2026-08-13 19:18:32.58067
72	41	3	2026-08-13 19:19:32.713827
73	73	1	2026-08-14 02:02:36.093625
74	74	1	2026-08-14 02:02:36.130321
75	10	2	2026-08-14 06:23:57.770632
76	11	2	2026-08-14 06:23:57.779625
77	12	2	2026-08-14 06:23:57.786062
78	13	2	2026-08-14 06:23:57.786062
79	14	2	2026-08-14 06:23:57.797023
80	15	2	2026-08-14 06:23:57.798944
81	16	2	2026-08-14 06:23:57.807741
82	17	2	2026-08-14 06:23:57.814869
83	18	2	2026-08-14 06:23:57.820963
84	19	2	2026-08-14 06:23:57.822949
85	20	2	2026-08-14 06:23:57.830637
86	21	2	2026-08-14 06:23:57.835591
87	22	2	2026-08-14 06:23:57.839769
88	23	2	2026-08-14 06:23:57.846481
89	24	2	2026-08-14 06:23:57.850223
90	25	2	2026-08-14 06:23:57.853872
91	26	2	2026-08-14 06:23:57.861058
92	27	2	2026-08-14 06:23:57.866357
93	28	2	2026-08-14 06:23:57.87001
94	47	2	2026-08-14 06:23:57.871517
95	57	2	2026-08-14 06:23:57.879625
96	75	2	2026-08-16 14:16:23.915976
97	59	2	2026-08-16 14:17:10.396198
98	72	2	2026-08-16 15:23:46.042285
99	42	2	2026-08-16 15:29:03.873667
100	43	2	2026-08-16 15:29:03.888492
101	44	2	2026-08-16 15:29:03.895015
102	45	2	2026-08-16 15:29:03.900581
103	64	2	2026-08-16 15:29:03.906541
104	68	2	2026-08-16 15:29:03.913296
105	70	2	2026-08-16 15:29:03.918639
106	71	1	2026-08-16 15:36:42.821509
107	83	1	2026-08-16 17:55:37.387271
\.


--
-- Data for Name: Messages; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Messages" (message_id, chat_id, sender_id, content, status, sent_at, reply_to_message_id, reply_preview, reply_sender_name) FROM stdin;
1	1	1	bsjejbdbd	seen	2026-07-10 21:21:48.177323	\N	\N	\N
2	1	2	sjsjebrbbrn	seen	2026-07-10 21:22:30.299148	\N	\N	\N
3	1	2	jdjebdd	seen	2026-07-10 21:22:34.398748	\N	\N	\N
4	1	2	ndndndnr	seen	2026-07-10 21:22:35.726837	\N	\N	\N
5	1	2	cool	seen	2026-07-25 18:52:33.455912	\N	\N	\N
6	1	1	hsskjdd	seen	2026-07-31 17:57:40.031687	\N	\N	\N
7	1	1	djdjdjd	seen	2026-07-31 17:57:41.464773	\N	\N	\N
10	1	1	sta	sent	2026-07-31 18:37:47.753958	4	ndndndnr	Filip
11	1	1	sta	sent	2026-07-31 18:37:58.32812	2	sjsjebrbbrn	Filip
12	1	1	sjshsh	sent	2026-07-31 23:30:04.861106	4	ndndndnr	Filip
13	1	1	sa	sent	2026-07-31 23:30:22.303229	\N	\N	\N
14	1	1	s	sent	2026-07-31 23:30:22.652024	\N	\N	\N
15	1	1	ss	sent	2026-07-31 23:30:22.953089	\N	\N	\N
16	1	1	s	sent	2026-07-31 23:30:23.213858	\N	\N	\N
17	1	1	s	sent	2026-07-31 23:30:23.631449	\N	\N	\N
18	1	1	s	sent	2026-07-31 23:30:23.992956	\N	\N	\N
19	1	1	ss	sent	2026-07-31 23:30:24.343702	\N	\N	\N
20	1	1	ss	sent	2026-07-31 23:30:24.739601	\N	\N	\N
21	1	1	ss	sent	2026-07-31 23:30:25.038863	\N	\N	\N
22	1	1	sss	sent	2026-07-31 23:30:25.183324	\N	\N	\N
23	1	1	s	sent	2026-07-31 23:30:25.666891	\N	\N	\N
24	1	1	a	sent	2026-07-31 23:30:25.864105	\N	\N	\N
25	1	1	a	sent	2026-07-31 23:30:26.220523	\N	\N	\N
26	1	1	r	sent	2026-07-31 23:30:26.657512	\N	\N	\N
27	1	1	fr	sent	2026-07-31 23:30:27.005919	\N	\N	\N
28	1	1	wtf	sent	2026-07-31 23:30:35.706746	2	sjsjebrbbrn	Filip
8	3	1	bsbsbd	seen	2026-07-31 18:37:27.580586	\N	\N	\N
9	3	1	bsbsn	seen	2026-07-31 18:37:29.013615	\N	\N	\N
29	4	2	Helloo	seen	2026-08-01 18:07:52.199101	\N	\N	\N
30	4	2	djff	seen	2026-08-01 18:07:53.689142	\N	\N	\N
31	4	2	f	seen	2026-08-01 18:07:53.955777	\N	\N	\N
32	4	2	f	seen	2026-08-01 18:07:54.218764	\N	\N	\N
33	4	2	f	seen	2026-08-01 18:07:54.45043	\N	\N	\N
34	4	2	f	seen	2026-08-01 18:07:54.792019	\N	\N	\N
35	4	2	ss	seen	2026-08-01 18:07:55.169283	\N	\N	\N
36	4	2	sr	seen	2026-08-01 18:07:55.53101	\N	\N	\N
37	4	2	gd	seen	2026-08-01 18:07:55.840342	\N	\N	\N
38	4	2	ss	seen	2026-08-01 18:07:56.172848	\N	\N	\N
39	4	2	g	seen	2026-08-01 18:07:56.468832	\N	\N	\N
40	4	2	f	seen	2026-08-01 18:07:56.681895	\N	\N	\N
47	1	4	hello guyw	sent	2026-08-02 14:06:40.631716	\N	\N	\N
52	3	1	Newest message sent at time: 14:56	sent	2026-08-02 14:59:40.654176	\N	\N	\N
53	4	1	aj smirela	sent	2026-08-02 15:08:50.142565	\N	\N	\N
54	3	1	cai	sent	2026-08-02 15:09:04.485255	\N	\N	\N
55	3	1	jed	sent	2026-08-02 15:09:09.32291	\N	\N	\N
56	3	1	hd	sent	2026-08-02 15:09:10.352514	\N	\N	\N
57	1	1	j	sent	2026-08-02 15:10:47.62412	\N	\N	\N
58	10	1	hello	sent	2026-08-02 15:28:25.451662	\N	\N	\N
59	9	1	why nit working	sent	2026-08-02 15:32:38.319072	\N	\N	\N
60	2	1	ehe	sent	2026-08-02 15:33:06.619022	\N	\N	\N
48	11	4	hi Filip	seen	2026-08-02 14:11:00.598499	\N	\N	\N
61	11	4	okat	seen	2026-08-02 15:33:44.149869	\N	\N	\N
62	11	2	Hello	seen	2026-08-02 15:34:38.289372	\N	\N	\N
63	11	2	why are you texting me?	seen	2026-08-02 15:34:44.594652	\N	\N	\N
49	12	4	hi rosa	seen	2026-08-02 14:11:44.769125	\N	\N	\N
66	12	1	okay	sent	2026-08-02 15:44:33.883534	\N	\N	\N
67	3	1	hi guys kets habg out	sent	2026-08-02 15:44:46.338464	\N	\N	\N
69	12	1	hez	sent	2026-08-11 15:39:30.06426	\N	\N	\N
41	6	2	So we wanna catch some fish	seen	2026-08-01 18:08:09.39467	\N	\N	\N
46	8	1	cao cigane	seen	2026-08-01 19:59:25.251886	\N	\N	\N
65	8	1	okaz	seen	2026-08-02 15:44:28.98277	\N	\N	\N
75	6	3	heyyy	sent	2026-08-13 19:19:36.397855	\N	\N	\N
73	8	3	cao rossa	seen	2026-08-13 19:18:36.666432	\N	\N	\N
74	8	3	you so beatifull	seen	2026-08-13 19:18:46.105791	\N	\N	\N
76	8	1	I have a bf 	sent	2026-08-14 02:03:31.587648	\N	\N	\N
77	8	1	And he is better then you	sent	2026-08-14 02:03:40.223026	\N	\N	\N
78	8	1	so....	sent	2026-08-14 02:03:43.943025	\N	\N	\N
79	9	2	its working now	sent	2026-08-16 14:17:19.047357	\N	\N	\N
80	9	2	i fixed it	sent	2026-08-16 14:17:25.826152	\N	\N	\N
72	40	3	cao brate kako je	seen	2026-08-13 19:18:18.533107	\N	\N	\N
81	40	2	aj ne smaraj	sent	2026-08-16 15:24:03.388807	\N	\N	\N
82	40	2	luice	sent	2026-08-16 15:24:07.160948	\N	\N	\N
42	7	1	cao	seen	2026-08-01 19:03:25.371045	\N	\N	\N
43	7	1	cao cao	seen	2026-08-01 19:08:48.779989	\N	\N	\N
44	7	1	hello	seen	2026-08-01 19:30:47.928992	\N	\N	\N
45	7	1	hello	seen	2026-08-01 19:45:50.159332	\N	\N	\N
64	7	1	okaz	seen	2026-08-02 15:44:21.403473	\N	\N	\N
68	7	1	hello	seen	2026-08-11 15:00:10.184064	\N	\N	\N
70	7	1	cao cofi	seen	2026-08-13 17:28:26.72203	\N	\N	\N
83	1	2	sbshshd	sent	2026-08-16 15:30:31.827517	\N	\N	\N
71	39	5	hejj	seen	2026-08-13 17:58:57.917048	\N	\N	\N
\.


--
-- Data for Name: User_Images; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."User_Images" (id, user_id, image_path) FROM stdin;
1	2	2d39b015-0eb5-4ecb-bd47-7ab4d5dc6363_upload9208125845243120519.jpg
2	1	a4472af5-1899-405b-89fc-648aed5684b4_upload282814226042439633.jpg
3	1	c8309dd5-e564-4913-bdf0-47ca563d98e1_upload229604172774844478.jpg
4	3	f3556d65-b456-4037-9b76-c47cc2993682_upload405511289442134531.jpg
5	3	a98aa9d7-57be-4422-b5b9-adc3c44d3d63_upload8970136026140685761.jpg
6	3	1194a5a9-360b-49b2-b74c-4f866bfccd4f_upload8689400436194795208.jpg
7	4	ee998880-8e3f-43a0-b271-4e59b8f8f72e_upload5839047498909281194.jpg
8	4	57ab5c72-a588-46a4-9077-f42fac97285e_upload767961635683662049.jpg
9	2	d5b7f61b-8f8e-437e-ac8d-890fcb672760_upload8501920450841729097.jpg
10	1	78c454c2-e257-4cb3-8d75-ec81d65b3f27_upload4367535989477267988.jpg
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Users" (id, name, country_of_origin, email, password_hash, profile_image_id, created_at, bio) FROM stdin;
3	Djura	Serbia	test64	$2a$10$4JeDw9GSftnn8wr0EuHWLe3x1VwB.VRh2mNvXzWUtOMt08MYQ4rii	6	2026-07-31 18:05:54.415034	
1	Rossa	Tanzania	test	$2a$10$DVfFVVbXpvWxTXKXyFY9tOQBAJAGnzcsUdraiOfWe4nZksWhE/DbK	2	2026-07-10 21:19:12.468155	😎🐱😎🐱👍🙂👍😂🫂💋💪💩😅😎💩😎🤬🤬👌🌏🤫🌏🤫😂💪😢😏😎🙂👋🐱❤️😇❤️👍💋😄👿👌😢💪💪😐👌🙏🙏👻😐👍🤝😄🫏🐺🐎🐺🦮🦊🦮🐴🐃🦧🐃🦧🏏🎎🥎🎍🥎🎍🎗🏆🎈🎗↘️🛃↘️🛃⬇️🚳🚸🚳🚻🚮↘️🚮↘️👟🩳🥾🩳🥾👘
4	Iva	Serbia	iva	$2a$10$aNEiEoBuhYBGviHOuFzl0en3H1qHhpAYKjAEU7O6NfbbPcPMeAt5u	7	2026-08-02 14:04:48.461041	#&#*#&#;;÷@>*@93039👕👖👛👛🇧🇭🇦🇽🔘🔻💠
2	Filip	Serbia	test1	$2a$10$h42TsmI/deXq7.yde9PaHunmqHjFPikf52EwixymvlLPiumUJ7Pra	9	2026-07-10 21:22:14.822614	hdhdbdbdbffg
5	Mića	Serbia	test007	$2a$10$ilw5Up2oYyyloiyieYBNZu0Dp1KTXYmEsX4zPNQzhXHpnmHsU.XL.	\N	2026-08-13 17:49:54.259235	\N
\.


--
-- Data for Name: chat_users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.chat_users (id, chat_id, joined_at, user_id) FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.notifications (notification_id, user_id, type, title, message, actor_user_id, activity_id, chat_id, message_id, is_seen, created_at) FROM stdin;
2	1	FRIEND_REQUEST_RECEIVED	New friend request	You received a friend request	5	\N	\N	\N	t	2026-08-13 17:58:49.705385
4	5	FRIEND_REQUEST_ACCEPTED	Friend request accepted	Your friend request was accepted	1	\N	\N	\N	t	2026-08-13 18:04:39.924696
13	5	NEW_MESSAGE	New message	Djura sent you a message	3	\N	6	75	f	2026-08-13 19:19:36.409376
1	2	NEW_MESSAGE	New message	Rossa sent you a message	1	\N	7	70	t	2026-08-13 17:28:26.789768
11	1	ACTIVITY_JOINED	Activity joined	Djura joined your activity	3	10	\N	\N	t	2026-08-13 19:19:26.061749
10	1	NEW_MESSAGE	New message	Djura sent you a message	3	\N	8	74	t	2026-08-13 19:18:46.128529
8	1	FRIEND_REQUEST_RECEIVED	New friend request	Djura has sent you a friend request	3	\N	\N	\N	t	2026-08-13 19:18:29.923483
14	3	FRIEND_REQUEST_ACCEPTED	Friend request accepted	Rossa accepted your friend request	1	\N	\N	\N	f	2026-08-14 02:02:57.2044
6	1	ACTIVITY_JOINED	Activity joined	Djura joined your activity	3	7	\N	\N	t	2026-08-13 19:17:47.602073
9	1	NEW_MESSAGE	New message	Djura sent you a message	3	\N	8	73	t	2026-08-13 19:18:36.677729
15	3	NEW_MESSAGE	New message	Rossa sent you a message	1	\N	8	76	f	2026-08-14 02:03:31.63498
16	3	NEW_MESSAGE	New message	Rossa sent you a message	1	\N	8	77	f	2026-08-14 02:03:40.237252
17	3	NEW_MESSAGE	New message	Rossa sent you a message	1	\N	8	78	f	2026-08-14 02:03:43.958518
5	2	ACTIVITY_JOINED	Activity joined	Djura joined your activity	3	6	\N	\N	t	2026-08-13 19:17:34.208821
18	1	ACTIVITY_JOINED	Activity joined	Filip joined your Jumping off monas with parachute activity	2	7	9	\N	f	2026-08-14 02:28:04.076332
19	1	ACTIVITY_JOINED	Activity joined	Filip joined your Hanging out activity	2	3	3	\N	f	2026-08-14 02:28:06.305952
20	1	ACTIVITY_JOINED	Activity joined	Filip joined your ejdjd activity	2	11	38	\N	t	2026-08-14 02:28:08.501035
12	2	NEW_MESSAGE	New message	Djura sent you a message	3	\N	6	75	t	2026-08-13 19:19:36.409376
21	3	FRIEND_REQUEST_ACCEPTED	Friend request accepted	Filip accepted your friend request	2	\N	\N	\N	f	2026-08-16 14:16:36.44954
22	5	FRIEND_REQUEST_ACCEPTED	Friend request accepted	Filip accepted your friend request	2	\N	\N	\N	f	2026-08-16 14:16:54.668753
23	1	NEW_MESSAGE	New message	Filip sent you a message	2	\N	9	79	f	2026-08-16 14:17:19.10197
24	3	NEW_MESSAGE	New message	Filip sent you a message	2	\N	9	79	f	2026-08-16 14:17:19.103343
25	1	NEW_MESSAGE	New message	Filip sent you a message	2	\N	9	80	f	2026-08-16 14:17:25.839206
26	3	NEW_MESSAGE	New message	Filip sent you a message	2	\N	9	80	f	2026-08-16 14:17:25.839206
7	2	FRIEND_REQUEST_RECEIVED	New friend request	Djura has sent you a friend request	3	\N	\N	\N	t	2026-08-13 19:18:10.01066
3	2	FRIEND_REQUEST_RECEIVED	New friend request	You received a friend request	5	\N	\N	\N	t	2026-08-13 18:01:14.115448
27	3	NEW_MESSAGE	New message	Filip sent you a message	2	\N	40	81	f	2026-08-16 15:24:03.397164
28	3	NEW_MESSAGE	New message	Filip sent you a message	2	\N	40	82	f	2026-08-16 15:24:07.174642
29	1	NEW_MESSAGE	New message	Filip sent you a message	2	\N	1	83	f	2026-08-16 15:30:31.843637
30	3	NEW_MESSAGE	New message	Filip sent you a message	2	\N	1	83	f	2026-08-16 15:30:31.848285
31	4	NEW_MESSAGE	New message	Filip sent you a message	2	\N	1	83	f	2026-08-16 15:30:31.849176
\.


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.refresh_tokens (id, created_at, expires_at, revoked, token, user_id) FROM stdin;
1	2026-07-10 21:21:02.719029	2026-08-09 21:21:02.719029	f	66a49a03-adbf-49b8-a804-6a58f264cbff	1
2	2026-07-10 21:22:19.785763	2026-08-09 21:22:19.785763	f	26ae5b63-c31a-4f56-9c5a-0535b52773e0	2
3	2026-07-10 21:23:23.126561	2026-08-09 21:23:23.126561	f	1ff03152-428a-499a-9d87-b755ec14d3ae	1
4	2026-07-18 22:46:42.605136	2026-08-17 22:46:42.605136	f	fcc9cd70-73f2-42b9-ada3-c3d95251f32f	1
5	2026-07-18 22:55:18.854327	2026-08-17 22:55:18.854327	f	ea32e9e7-3a57-4785-a77c-889e6d35283d	1
6	2026-07-18 22:55:55.183788	2026-08-17 22:55:55.183788	f	f48bcd61-0f95-49a3-82c4-1406fd6c910f	1
7	2026-07-25 15:09:42.169386	2026-08-24 15:09:42.169386	f	04c215a1-c388-45aa-8914-c90fbc98bc9f	1
8	2026-07-25 15:14:45.182165	2026-08-24 15:14:45.182165	f	88ec9e44-3342-41bd-b233-a95ea2b2831e	1
9	2026-07-25 18:51:55.968193	2026-08-24 18:51:55.968193	f	e8121df4-a51b-4811-9681-7893100eda2c	2
10	2026-07-25 18:55:44.529203	2026-08-24 18:55:44.529203	f	338ca656-2037-4a52-b58a-40c9b2c145e8	2
11	2026-07-25 18:56:21.932502	2026-08-24 18:56:21.932502	f	e4c317ca-26df-4899-b114-3f22ea0040e9	1
12	2026-07-25 19:00:58.48088	2026-08-24 19:00:58.48088	f	5c94c2fc-6fa7-4575-8b2c-2dc572ae3965	1
13	2026-07-31 17:42:23.77025	2026-08-30 17:42:23.77025	f	dec1df7a-be4f-4085-9b5e-68f7f5a4c375	1
14	2026-07-31 17:45:15.67121	2026-08-30 17:45:15.67121	f	488ca3a3-793a-42e2-9a0f-423c3dc94068	1
15	2026-07-31 17:50:09.257775	2026-08-30 17:50:09.257775	f	6952c925-d832-41fe-951f-d056dc018b1c	1
16	2026-07-31 17:56:18.81312	2026-08-30 17:56:18.81312	f	fd28c87c-1456-46dd-8c4e-a855d5f19516	1
17	2026-07-31 17:57:10.933665	2026-08-30 17:57:10.933665	f	c6b97d76-e2f8-4cb1-92d6-ba84bc527730	1
18	2026-07-31 18:00:55.290582	2026-08-30 18:00:55.290582	f	8a9ab666-37ae-4500-93f2-6c5a321bbe89	1
19	2026-07-31 18:04:41.089542	2026-08-30 18:04:41.089542	f	ad23495b-91b2-4f8b-8b43-0119816a1926	1
20	2026-07-31 18:06:01.154473	2026-08-30 18:06:01.154473	f	e3212b15-a21b-4c1d-9fbc-d876cc8cd904	3
21	2026-07-31 18:06:59.321666	2026-08-30 18:06:59.321666	f	868e7187-df79-4d2b-9168-5d33dce7565c	2
22	2026-07-31 18:08:06.843591	2026-08-30 18:08:06.843591	f	17a18458-2d7f-4252-9943-21aebb7ba525	1
23	2026-07-31 18:12:59.356465	2026-08-30 18:12:59.356465	f	ad84a623-101f-47d4-9d63-df9ea5bb14e7	1
24	2026-07-31 18:16:03.887499	2026-08-30 18:16:03.887499	f	a5ce9d89-ddcb-4010-a610-2bebbdf88c40	1
25	2026-07-31 18:16:34.940355	2026-08-30 18:16:34.940355	f	a7fc5671-9508-446c-b5dd-eb77a67000c1	1
26	2026-07-31 18:17:29.700365	2026-08-30 18:17:29.700365	f	bc4bd1e3-6619-42f7-aa18-460d6f9ce0c1	1
27	2026-07-31 18:18:40.348079	2026-08-30 18:18:40.348079	f	f9d484ee-b490-4b71-a3e4-2d1f8628385f	3
28	2026-07-31 18:28:32.922004	2026-08-30 18:28:32.922004	f	98a180cc-db8e-42be-9175-dd4710f0d6f6	1
29	2026-07-31 18:31:38.068841	2026-08-30 18:31:38.068841	f	03e16b3f-71f9-41b0-8076-dda2991a514b	1
30	2026-07-31 18:34:40.328325	2026-08-30 18:34:40.328325	f	cac713bb-3a7d-4bb4-87f5-bcf9c8078d53	1
31	2026-07-31 18:35:42.904848	2026-08-30 18:35:42.904848	f	abecb616-ed9b-4cd1-a221-d0b5513f6771	3
32	2026-07-31 18:36:52.855972	2026-08-30 18:36:52.855972	f	63802c04-496f-40e6-b671-c4c7925eda1f	1
33	2026-07-31 23:23:29.304519	2026-08-30 23:23:29.304519	f	f6bb9d65-cf4f-443e-b5e5-9499ce81c51a	1
34	2026-07-31 23:28:45.345808	2026-08-30 23:28:45.345808	f	f8d4f7d5-dfda-4b14-ac98-f79cf35ae377	1
35	2026-08-01 16:26:49.735886	2026-08-31 16:26:49.737175	f	5024bd3a-8de8-4a59-9a32-61e99b52e0e1	1
36	2026-08-01 17:34:35.945093	2026-08-31 17:34:35.945093	f	90931cc2-85be-4db4-8471-b30f930f420c	1
37	2026-08-01 17:40:06.606416	2026-08-31 17:40:06.606416	f	0102ffda-8dee-45be-b29f-f005b9a4e7ca	1
38	2026-08-01 17:58:53.934184	2026-08-31 17:58:53.934184	f	a088eb68-f17f-4695-b016-40258ecfe7c1	3
39	2026-08-01 18:06:23.243861	2026-08-31 18:06:23.243861	f	790c1766-17fc-4f95-bca6-db9bbbd0596b	2
40	2026-08-01 18:31:19.472255	2026-08-31 18:31:19.472255	f	82586b78-2c1f-4a02-88d7-e3f466ea039d	1
41	2026-08-01 19:00:50.353418	2026-08-31 19:00:50.353418	f	f968c8a7-ecfe-4929-9337-105230d42427	1
42	2026-08-01 19:03:07.843503	2026-08-31 19:03:07.843503	f	d3d3f318-d16b-45ce-8bc4-2974e73c82c2	1
43	2026-08-01 19:03:51.207702	2026-08-31 19:03:51.207702	f	4693fe66-83be-44e7-8aa8-9688019e7110	1
44	2026-08-01 19:08:38.093938	2026-08-31 19:08:38.093938	f	b41a2ec0-df6c-44c7-ad1a-d1b17de20b8b	1
45	2026-08-01 19:30:37.918973	2026-08-31 19:30:37.918973	f	b5566401-6444-4fad-831e-870d71739963	1
46	2026-08-01 19:45:41.368456	2026-08-31 19:45:41.368456	f	8b0b9aca-8934-46b0-8077-a49362de5ef9	1
47	2026-08-01 19:51:09.848539	2026-08-31 19:51:09.848539	f	95c6fc90-52ac-4926-abe0-78763c23edf0	1
48	2026-08-01 19:51:36.084008	2026-08-31 19:51:36.084008	f	46f4f085-5d73-4112-ae11-ba6ca63ea55e	1
49	2026-08-01 19:54:02.956382	2026-08-31 19:54:02.956382	f	8b5ca94d-1bb1-4d3d-a5f1-e60dc03511cf	1
50	2026-08-01 19:58:10.40171	2026-08-31 19:58:10.40171	f	3ca5cce7-42f6-447f-94f2-e7e2ccacc016	1
51	2026-08-01 20:05:49.446839	2026-08-31 20:05:49.446839	f	20eb656c-e47e-4a43-8bc5-b54d41a3a188	1
52	2026-08-01 20:06:22.984295	2026-08-31 20:06:22.984295	f	5a73e948-576f-4bbe-94d1-349ba156dcd9	1
53	2026-08-01 20:10:42.63283	2026-08-31 20:10:42.63283	f	b7afb609-eea6-4196-9530-6582e2f1267f	1
54	2026-08-01 20:14:16.852494	2026-08-31 20:14:16.852494	f	88665889-d5eb-4538-b9b8-e8d6a5c1119b	1
55	2026-08-01 20:48:18.403181	2026-08-31 20:48:18.403181	f	5ded04b4-ca79-45e3-8c57-a11e59b8762c	1
56	2026-08-01 20:58:37.758954	2026-08-31 20:58:37.758954	f	211fafe6-9538-4d1b-972f-44178a605d0b	1
57	2026-08-01 21:04:52.977217	2026-08-31 21:04:52.977217	f	f6e05525-853f-40e1-852e-b6aeb3b4297c	1
58	2026-08-02 13:28:16.030706	2026-09-01 13:28:16.030706	f	0f676fd3-aa9c-4d23-8818-f8e5e5c8d437	1
59	2026-08-02 13:52:32.115084	2026-09-01 13:52:32.115084	f	93bbe9a0-4eb6-45ce-8cbf-5a663e2ce731	1
60	2026-08-02 14:03:44.214268	2026-09-01 14:03:44.214268	f	cd904c40-42a7-4157-9b35-95646f93c584	1
61	2026-08-02 14:04:56.012401	2026-09-01 14:04:56.012401	f	42ee2bab-e4ea-4fb0-9c2c-efa2f00b7a58	4
62	2026-08-02 14:07:35.973298	2026-09-01 14:07:35.973298	f	b0cc9b3c-6c0a-4d69-9ab3-2caaa0010bc1	4
63	2026-08-02 14:09:51.13544	2026-09-01 14:09:51.13544	f	bb45564a-e3b1-423f-8c15-7ad636980771	4
64	2026-08-02 14:10:35.948291	2026-09-01 14:10:35.948291	f	d5f31a00-2d12-4f9c-89e6-e5143abbb967	4
65	2026-08-02 14:11:26.553036	2026-09-01 14:11:26.553036	f	b5fd7fc1-3e96-47a9-91b6-10247bce69cf	4
66	2026-08-02 14:28:43.080608	2026-09-01 14:28:43.080608	f	fd20d451-7c59-4705-b65d-73ade301ce49	1
67	2026-08-02 14:56:39.578594	2026-09-01 14:56:39.578594	f	56938de5-7330-402a-8f69-6aead1a2124e	1
68	2026-08-02 15:08:37.941405	2026-09-01 15:08:37.941405	f	1975b80b-b28c-444a-b5e6-178ebb4d945b	1
69	2026-08-02 15:28:11.747707	2026-09-01 15:28:11.747707	f	659822b9-5360-4df6-9775-7dca67c13e3b	1
70	2026-08-02 15:29:14.410449	2026-09-01 15:29:14.410449	f	8d3cfb41-967a-4aa1-ab9e-27d2f7e54a4a	1
71	2026-08-02 15:32:19.252184	2026-09-01 15:32:19.252184	f	35af720d-352d-4dfb-aebf-fa0d84357314	1
72	2026-08-02 15:33:21.89966	2026-09-01 15:33:21.900682	f	fca26a7d-08df-4e1b-9ed6-56edddf0bb07	4
73	2026-08-02 15:33:58.904712	2026-09-01 15:33:58.904712	f	06e59cc5-39c4-492e-a4e1-9d7692ce6ac2	4
74	2026-08-02 15:34:25.460341	2026-09-01 15:34:25.460341	f	38c80bcc-265a-4c7f-8ad3-de26de5e85e0	2
75	2026-08-02 15:34:57.066639	2026-09-01 15:34:57.066639	f	22ba604d-76cb-4af4-85c5-cc27ef3b1c6b	4
76	2026-08-02 15:39:18.831199	2026-09-01 15:39:18.831199	f	c8697908-a093-4276-975d-ed7be922788c	1
77	2026-08-11 14:56:56.851106	2026-09-10 14:56:56.851106	f	901354cf-08d6-4eea-b06b-db241dc044f7	1
78	2026-08-11 15:06:15.192945	2026-09-10 15:06:15.192945	f	f4f1f5a6-694d-45b5-8d3e-38acd5ded44f	2
79	2026-08-11 15:39:19.95643	2026-09-10 15:39:19.95643	f	c58fae09-e076-451e-b633-e062c1d12690	1
80	2026-08-13 15:17:57.02033	2026-09-12 15:17:57.02033	f	7af14f79-6d03-4615-b8d9-a6409f072bc0	1
81	2026-08-13 15:18:12.94086	2026-09-12 15:18:12.94086	f	a8c9f88f-342c-4ed0-a079-33ba41090279	1
82	2026-08-13 15:23:44.602158	2026-09-12 15:23:44.602158	f	6e040ad9-07d0-42d7-875b-2e333f8b0a84	1
83	2026-08-13 17:28:15.785422	2026-09-12 17:28:15.785422	f	fa7daee2-fe67-4fdf-932e-6484dc691e52	1
84	2026-08-13 17:50:01.356202	2026-09-12 17:50:01.356202	f	e2c137f5-d4f2-47d9-b8f7-d4e850ef7090	5
85	2026-08-13 18:03:48.307737	2026-09-12 18:03:48.307737	f	af5e9fa9-87a0-4ed2-a201-0a0c2d770fdc	1
86	2026-08-13 18:32:27.733702	2026-09-12 18:32:27.733702	f	78384d72-8549-43ba-b28e-0289a8814941	1
87	2026-08-13 18:32:56.925794	2026-09-12 18:32:56.925794	f	d05a7ee0-7eff-4bd5-a468-b88b58462c3d	5
88	2026-08-13 19:17:10.104116	2026-09-12 19:17:10.104116	f	b7053230-adae-4d5a-8ca7-ae4efc992a4b	3
89	2026-08-13 19:20:10.605678	2026-09-12 19:20:10.605678	f	8e71dab4-2c49-49e7-8527-d98bb0ea2c59	2
90	2026-08-14 00:24:10.051618	2026-09-13 00:24:10.051618	f	82140576-fe77-41de-bee6-7c484429f82f	1
91	2026-08-14 02:02:27.274744	2026-09-13 02:02:27.274744	f	2fa377e4-aeb5-4dd6-a8a0-b808ddbbc113	1
92	2026-08-14 02:09:55.706875	2026-09-13 02:09:55.706875	f	78136eab-de42-48d8-b23c-40d0ef811e29	2
93	2026-08-14 02:16:44.456814	2026-09-13 02:16:44.456814	f	04d6c32e-b642-4921-a69c-3c6ba920abe7	2
94	2026-08-14 02:20:33.761522	2026-09-13 02:20:33.761522	f	492dbd1a-d22b-4284-a118-1f9ab37d3b10	2
95	2026-08-14 02:23:07.805854	2026-09-13 02:23:07.805854	f	08a2e884-6786-4ebf-bb48-aa0d937c0824	2
96	2026-08-14 02:28:29.565703	2026-09-13 02:28:29.565703	f	38e39b40-573b-47ae-b06f-933b84563092	1
97	2026-08-14 06:22:00.423502	2026-09-13 06:22:00.423502	f	b0f9a18f-810a-4e4b-9112-547e4a708361	2
98	2026-08-16 14:16:14.59719	2026-09-15 14:16:14.59719	f	1386f76d-9e71-4326-b50a-6604956fd9d1	2
99	2026-08-16 14:16:48.596411	2026-09-15 14:16:48.596411	f	50d747ac-9612-4fbf-b8d3-0a0a3b1cfa8a	2
100	2026-08-16 15:15:30.550641	2026-09-15 15:15:30.550641	f	9230f720-1e06-4bae-93ad-e7a44dd434cf	2
101	2026-08-16 15:21:21.636966	2026-09-15 15:21:21.636966	f	df7e63d5-c361-492b-9921-59b0665ffc22	2
102	2026-08-16 15:23:32.537654	2026-09-15 15:23:32.537654	f	3ad054c0-079c-49e6-a94b-c4fc826fcea5	2
103	2026-08-16 15:28:35.205913	2026-09-15 15:28:35.205913	f	21237690-125c-486b-8d51-c37e6f56d62c	2
104	2026-08-16 15:36:02.207641	2026-09-15 15:36:02.207641	f	e4fd5e82-4756-432c-b671-e92596caf82c	1
105	2026-08-16 17:55:22.288709	2026-09-15 17:55:22.288709	f	44947104-7235-4689-bf13-41208c0733e9	1
106	2026-08-16 17:58:30.041804	2026-09-15 17:58:30.041804	f	9678afc3-dc44-4236-b868-11b05bbed989	2
107	2026-08-16 18:01:45.697775	2026-09-15 18:01:45.697775	f	a2e9ceeb-8d3d-42b8-a149-fb0a789fde7f	2
108	2026-08-16 18:02:28.76043	2026-09-15 18:02:28.76043	f	95cb92c5-ee9c-4501-a8ed-650c9e951211	1
109	2026-08-16 18:04:24.92847	2026-09-15 18:04:24.92847	f	4a599e92-cc8f-4d7b-a7b9-4b01dbcab123	1
110	2026-08-16 18:06:24.460924	2026-09-15 18:06:24.460924	f	ee0a3bba-b19d-4cf3-8ac1-1d871fd0567c	2
111	2026-08-16 18:09:09.741533	2026-09-15 18:09:09.741533	f	dbf8d14f-0e5f-4995-ad26-20750c950775	1
112	2026-08-16 18:28:53.437254	2026-09-15 18:28:53.437254	f	b2c12c28-f9d7-4fee-8282-37081f761655	1
113	2026-08-16 18:48:52.735593	2026-09-15 18:48:52.735593	f	198d14f8-47ca-440b-95c3-74c84358fb79	1
114	2026-08-16 18:57:16.511958	2026-09-15 18:57:16.511958	f	79919dbc-0234-4cfb-9e5e-a4950b153000	1
115	2026-08-16 19:00:32.378699	2026-09-15 19:00:32.378699	f	a71f0d0e-7953-4958-be67-df35b7915517	1
116	2026-08-16 19:02:40.759352	2026-09-15 19:02:40.759352	f	c6b07042-14c7-47ac-b4b4-9de20c2d2154	1
117	2026-08-16 19:09:03.36201	2026-09-15 19:09:03.36301	f	c022f83a-0b6c-482f-b252-fac274fb9aba	1
118	2026-08-16 19:19:11.298576	2026-09-15 19:19:11.298576	f	85579fb6-a4f5-4176-b499-5a0bdeb7698e	1
119	2026-08-16 19:23:17.323526	2026-09-15 19:23:17.323526	f	27c8f342-f649-4453-a2f6-098490ed3c16	1
120	2026-08-16 19:24:22.971333	2026-09-15 19:24:22.971333	f	f8728538-559c-45a2-9e08-f1eaefe60aa1	1
\.


--
-- Name: Activity_activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Activity_activity_id_seq"', 15, true);


--
-- Name: Chat_Users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Chat_Users_id_seq"', 46, true);


--
-- Name: Chats_chat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Chats_chat_id_seq"', 44, true);


--
-- Name: Friendships_friendship_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Friendships_friendship_id_seq"', 8, true);


--
-- Name: Message_Seen_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Message_Seen_id_seq"', 107, true);


--
-- Name: Messages_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Messages_message_id_seq"', 83, true);


--
-- Name: User_Images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."User_Images_id_seq"', 10, true);


--
-- Name: Users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Users_id_seq"', 5, true);


--
-- Name: chat_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.chat_users_id_seq', 1, false);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.notifications_notification_id_seq', 31, true);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 120, true);


--
-- Name: Activity_Users Activity_Users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity_Users"
    ADD CONSTRAINT "Activity_Users_pkey" PRIMARY KEY (activity_id, user_id);


--
-- Name: Activity Activity_chat_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity"
    ADD CONSTRAINT "Activity_chat_id_key" UNIQUE (chat_id);


--
-- Name: Activity Activity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity"
    ADD CONSTRAINT "Activity_pkey" PRIMARY KEY (activity_id);


--
-- Name: Chat_Users Chat_Users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chat_Users"
    ADD CONSTRAINT "Chat_Users_pkey" PRIMARY KEY (chat_id, user_id);


--
-- Name: Chats Chats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chats"
    ADD CONSTRAINT "Chats_pkey" PRIMARY KEY (chat_id);


--
-- Name: Friendships Friendships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Friendships"
    ADD CONSTRAINT "Friendships_pkey" PRIMARY KEY (friendship_id);


--
-- Name: Message_Seen Message_Seen_message_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen"
    ADD CONSTRAINT "Message_Seen_message_id_user_id_key" UNIQUE (message_id, user_id);


--
-- Name: Message_Seen Message_Seen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen"
    ADD CONSTRAINT "Message_Seen_pkey" PRIMARY KEY (id);


--
-- Name: Messages Messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "Messages_pkey" PRIMARY KEY (message_id);


--
-- Name: User_Images User_Images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User_Images"
    ADD CONSTRAINT "User_Images_pkey" PRIMARY KEY (id);


--
-- Name: Users Users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_email_key" UNIQUE (email);


--
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- Name: chat_users chat_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_users
    ADD CONSTRAINT chat_users_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);


--
-- Name: User_Images unique_user_image; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User_Images"
    ADD CONSTRAINT unique_user_image UNIQUE (user_id, image_path);


--
-- Name: Messages message_created_update_chat; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER message_created_update_chat AFTER INSERT ON public."Messages" FOR EACH ROW EXECUTE FUNCTION public.update_chat_last_message();


--
-- Name: Friendships Friendships_receiver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Friendships"
    ADD CONSTRAINT "Friendships_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public."Users"(id) ON DELETE CASCADE;


--
-- Name: Friendships Friendships_sender_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Friendships"
    ADD CONSTRAINT "Friendships_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public."Users"(id) ON DELETE CASCADE;


--
-- Name: Message_Seen Message_Seen_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen"
    ADD CONSTRAINT "Message_Seen_message_id_fkey" FOREIGN KEY (message_id) REFERENCES public."Messages"(message_id);


--
-- Name: Message_Seen Message_Seen_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen"
    ADD CONSTRAINT "Message_Seen_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Activity activity_chat_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity"
    ADD CONSTRAINT activity_chat_id_foreign FOREIGN KEY (chat_id) REFERENCES public."Chats"(chat_id);


--
-- Name: Activity activity_creator_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity"
    ADD CONSTRAINT activity_creator_id_foreign FOREIGN KEY (creator_id) REFERENCES public."Users"(id);


--
-- Name: Activity_Users activity_users_activity_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity_Users"
    ADD CONSTRAINT activity_users_activity_id_foreign FOREIGN KEY (activity_id) REFERENCES public."Activity"(activity_id);


--
-- Name: Activity_Users activity_users_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity_Users"
    ADD CONSTRAINT activity_users_user_id_foreign FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Chat_Users chat_users_chat_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chat_Users"
    ADD CONSTRAINT chat_users_chat_id_foreign FOREIGN KEY (chat_id) REFERENCES public."Chats"(chat_id);


--
-- Name: Chat_Users chat_users_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chat_Users"
    ADD CONSTRAINT chat_users_user_id_foreign FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: refresh_tokens fk_refresh_tokens_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Messages messages_chat_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT messages_chat_id_foreign FOREIGN KEY (chat_id) REFERENCES public."Chats"(chat_id);


--
-- Name: Messages messages_sender_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT messages_sender_id_foreign FOREIGN KEY (sender_id) REFERENCES public."Users"(id);


--
-- Name: notifications notifications_activity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public."Activity"(activity_id);


--
-- Name: notifications notifications_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public."Users"(id);


--
-- Name: notifications notifications_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public."Chats"(chat_id);


--
-- Name: notifications notifications_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_message_id_fkey FOREIGN KEY (message_id) REFERENCES public."Messages"(message_id);


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: User_Images user_images_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User_Images"
    ADD CONSTRAINT user_images_user_id_foreign FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Users users_profile_image_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_profile_image_id_foreign FOREIGN KEY (profile_image_id) REFERENCES public."User_Images"(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict xbFG3bOAPAHuSfDFsGhtT5jJLuBXz9BhB3co7JPnP9fDFi0Ciwpg51W1dFO0uJq

